#Metadata
application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

#Handlers
handlers:

- url: /css
  static_dir: css

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: .*
  script: main.app
  login: required

#Libraries
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
