#Metadata
application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: ye

#Handlers
handlers:

- url: ./*
  script: main.app
  login: required

- url: /scripts
  static_dir: scripts

#Libraries
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
